// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// coefficients_of_skewness
NumericVector coefficients_of_skewness(NumericMatrix matrix);
RcppExport SEXP autovarCore_coefficients_of_skewness(SEXP matrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type matrix(matrixSEXP);
    __result = Rcpp::wrap(coefficients_of_skewness(matrix));
    return __result;
END_RCPP
}
// portmanteau_test_statistics
NumericVector portmanteau_test_statistics(NumericMatrix matrix);
RcppExport SEXP autovarCore_portmanteau_test_statistics(SEXP matrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type matrix(matrixSEXP);
    __result = Rcpp::wrap(portmanteau_test_statistics(matrix));
    return __result;
END_RCPP
}
