// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP autovarCore_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(rcpp_hello_world());
    return __result;
END_RCPP
}
// portmanteau_test_statistics
NumericVector portmanteau_test_statistics(NumericMatrix matrix);
RcppExport SEXP autovarCore_portmanteau_test_statistics(SEXP matrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type matrix(matrixSEXP);
    __result = Rcpp::wrap(portmanteau_test_statistics(matrix));
    return __result;
END_RCPP
}
