# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Kurtosis coefficients.
#'
#' @param matrix the matrix of residuals.
#' @export
coefficients_of_kurtosis <- function(matrix) {
    .Call('autovarCore_coefficients_of_kurtosis', PACKAGE = 'autovarCore', matrix)
}

#' Skewness coefficients.
#'
#' @param matrix the matrix of residuals.
#' @export
coefficients_of_skewness <- function(matrix) {
    .Call('autovarCore_coefficients_of_skewness', PACKAGE = 'autovarCore', matrix)
}

#' An implementation of the portmanteau test.
#'
#' See the paper of Ljung-Box test for the used definition of autocorrelation.
#'
#' @param matrix the matrix of residuals or squared residuals.
#' @export
portmanteau_test_statistics <- function(matrix) {
    .Call('autovarCore_portmanteau_test_statistics', PACKAGE = 'autovarCore', matrix)
}

