# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Simple function using Rcpp
#'
#' @export
rcpp_hello_world <- function() {
    .Call('autovarCore_rcpp_hello_world', PACKAGE = 'autovarCore')
}

#' A faster version of portmanteau_test_statistic.
#'
#' @param matrix the matrix of residuals or squared residuals.
#' @export
portmanteau_test_statistics <- function(matrix) {
    .Call('autovarCore_portmanteau_test_statistics', PACKAGE = 'autovarCore', matrix)
}

